# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
    enableCustomProcessTemplate: true
    customWorkItemType: Flaw
    customPTActiveStatus: Working
    customPTNewStatus: Introducing
    customPTResolvedStatus: Resolved
    customPTCloseStatus: Closed

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Bash@3
  displayName: Auto-Packaing With Veracode CLI
  enabled: true
  inputs:
    targetType: "inline"
    script: |
      pwd
      export VERACODE_API_KEY_ID=$(VERACODE_API_ID)
      export VERACODE_API_KEY_SECRET=$(VERACODE_API_KEY)
      curl -fsS https://tools.veracode.com/veracode-cli/install | sh
      ./veracode package -s '$(Build.SourcesDirectory)' -o '$(build.artifactstagingdirectory)' -a true

- task: Veracode@3
  displayName: Upload & Scan
  enabled: false
  inputs:
    ConnectionDetailsSelection: 'Service Connection'
    AnalysisService: 'Veracode-Demo'
    veracodeAppProfile: 'nodegoat'
    version: 'nodegoat-$(build.buildNumber)'
    filepath: '$(build.artifactstagingdirectory)'
    sandboxName: 'Azure DevOps'
    createSandBox: true
    maximumWaitTime: '360'

- task: Veracode Flaw Importer@3
  enabled: true
  inputs:
    ConnectionDetailsSelection: 'Service Connection'
    AnalysisService: 'Veracode-Demo'
    veracodeAppProfile: 'nodegoat'
    sandboxName: 'Azure DevOps'
    scanType: 'Static, SCA'
    importType: 'All Unmitigated Flaws Violating Policy'
    workItemType: 'Issue'
    area: '$(system.teamProject)'
    overwriteAreaPathInWorkItemsOnImport: true
    iterationPath: '$(system.teamProject)'
    overwriteIterationPath: true
    flawImportLimit: '1000'
    customFields: 'Veracode'