# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, and scan

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
    enableCustomProcessTemplate: true
    customWorkItemType: Flaw
    customPTActiveStatus: Working
    customPTNewStatus: Introducing
    customPTResolvedStatus: Resolved
    customPTCloseStatus: Closed

steps:
- task: Bash@3
  displayName: Test OAuth Token
  enabled: false
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  inputs:
    targetType: 'inline'
    script: |
      # Install jq for JSON parsing
      apt-get update && apt-get install -y jq

      # Dynamically retrieve the org and project name
      ORG_URL=$(echo $(System.CollectionUri))
      YOUR_PROJECT_NAME=$(echo $(System.TeamProject))

      # Extract only the organization name from ORG_URL (removes "https://dev.azure.com/")
      YOUR_ORG_NAME=$(echo $ORG_URL | sed 's|https://dev.azure.com/||')
      echo "Testing Azure DevOps OAuth Token..."
      curl -s -u :$SYSTEM_ACCESSTOKEN \
        "https://dev.azure.com/$YOUR_ORG_NAME/$YOUR_PROJECT_NAME/_apis/projects?api-version=6.0" | jq .

- task: Bash@3
  displayName: Auto-Packaing With Veracode CLI
  enabled: true
  inputs:
    targetType: "inline"
    script: |
      pwd
      export VERACODE_API_KEY_ID=$(VERACODE_API_ID)
      export VERACODE_API_KEY_SECRET=$(VERACODE_API_KEY)
      curl -fsS https://tools.veracode.com/veracode-cli/install | sh
      ./veracode package -s '$(Build.SourcesDirectory)' -o '$(build.artifactstagingdirectory)' -a trust

- task: Bash@3
  displayName: Container Scanning
  enabled: false
  inputs:
    targetType: "inline"
    script: |
      export VERACODE_API_KEY_ID=$(VERACODE_API_ID)
      export VERACODE_API_KEY_SECRET=$(VERACODE_API_KEY)
      # ./veracode scan --source alpine:latest --type image --format table || true
      ./veracode scan --source vulnerables/web-dvwa --type image --format table || true

- task: Veracode@3
  displayName: Upload & Scan
  enabled: false
  inputs:
    ConnectionDetailsSelection: 'Service Connection'
    AnalysisService: 'Veracode-Demo'
    veracodeAppProfile: 'nodegoat'
    version: 'nodegoat-$(build.buildNumber)'
    filepath: '$(build.artifactstagingdirectory)'
    # sandboxName: 'Azure DevOps'
    createSandBox: false
    importResults: true
    maximumWaitTime: '360'

- task: Veracode@3
  displayName: Create App Profile and Upload & Scan
  enabled: false
  inputs:
    ConnectionDetailsSelection: 'Service Connection'
    AnalysisService: 'Veracode-Demo'
    veracodeAppProfile: 'nodegoat-customfields'
    version: '$(build.buildNumber)'
    filepath: '$(build.artifactstagingdirectory)'
    optargs: '-customfield name="Language" value="NodeJS"'
    createProfile: true
    maximumWaitTime: '360'

- task: VeracodePipelineScan@0
  displayName: Pipeline Scan Before Mitigations
  enabled: true
  inputs:
    serviceConnection: 'Veracode-Demo'
    fileToScan: '$(build.artifactstagingdirectory)/veracode-auto-pack-s-js.zip'
    additionalFlags: '--fail_on_severity="Very High, High"'

- task: Bash@3
  displayName: Retrieve Mitigations
  enabled: true
  inputs:
    targetType: "inline"
    script: |
      ls
      git clone https://github.com/tjarrettveracode/veracode-pipeline-mitigation
      # cd veracode-pipeline-mitigation
      ls
      pip install -r veracode-pipeline-mitigation/requirements.txt
      export VERACODE_API_KEY_ID=$(VERACODE_API_ID)
      export VERACODE_API_KEY_SECRET=$(VERACODE_API_KEY)
      python veracode-pipeline-mitigation/vcpipemit.py -an nodegoat --results '$(Build.SourcesDirectory)/pipeline.json'
      mv baseline-*.json baseline.json
      ls
      pwd




### DON'T EDIT
- task: VeracodePipelineScan@0
  displayName: Pipeline Scan After Mitigations
  enabled: true
  inputs:
    serviceConnection: 'Veracode-Demo'
    fileToScan: '$(build.artifactstagingdirectory)/veracode-auto-pack-s-js.zip'
    baselineFile: '$(Build.SourcesDirectory)/baseline.json'
    additionalFlags: '--fail_on_severity="Very High, High"'

- task: CmdLine@2
  displayName: SCA Agent-Based Scan
  enabled: false
  inputs:
    script: |
      export SCM_URI='https://nodegoat-ADO'
      export SRCCLR_API_TOKEN=$(SRCCLR_API_TOKEN)
      export scaDownloadUrl=https://download.srcclr.com/ci.sh
      export SCM_REF_TYPE=branch
      # make sure the branch name is set appropriately for the below scm_ref 
      export SCM_REF=master
      export SCM_REV=1.0
      curl -sSL $scaDownloadUrl | env bash -s scan --scm-uri $SCM_URI --scm-rev $SCM_REV --scm-ref $SCM_REF --scm-ref-type $SCM_REF_TYPE --update-advisor --allow-dirty

- task: Veracode Flaw Importer@3
  enabled: false
  inputs:
    ConnectionDetailsSelection: 'Service Connection'
    AnalysisService: 'Veracode-Demo'
    veracodeAppProfile: 'nodegoat'
    sandboxName: 'Azure DevOps'
    scanType: 'Static, SCA'
    importType: 'All Unmitigated Flaws Violating Policy'
    workItemType: 'Issue'
    area: '$(system.teamProject)'
    overwriteAreaPathInWorkItemsOnImport: true
    iterationPath: '$(system.teamProject)'
    overwriteIterationPath: true
    addCustomTag: 'external, internet facing'
    flawImportLimit: '1000'

